# Generated by Django 3.0.3 on 2020-10-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('CliEmail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CliName', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchContent', models.CharField(max_length=200)),
                ('SearchTime', models.DateTimeField(auto_now_add=True)),
                ('CliEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResModel.Client')),
            ],
        ),
    ]
