# Generated by Django 3.2 on 2020-10-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HubUser',
            fields=[
                ('UserEmail', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LitName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchContent', models.CharField(max_length=200)),
                ('SearchTime', models.DateTimeField(auto_now_add=True)),
                ('CliEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResModel.hubuser')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResModel.literature')),
                ('UserEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResModel.hubuser')),
            ],
        ),
    ]
